version: 1.0.{build}
image:
- Visual Studio 2015
clone_depth: 1

artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-
    set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%

    conda config --set always_yes yes --set changeps1 no

    conda update -q conda

    conda info -a

    conda install -c kx kdb

    conda info --base

deploy:

 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
