version: 1.0.{build}
image:
- Visual Studio 2017
clone_depth: 1

artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-
    start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
    set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
