version: 1.0.{build}
image:
- Visual Studio 2015
clone_depth: 1

artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-
    set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
    #installing embedPy with conda
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda info -a
    conda install -c kx embedpy
    conda info --base
    #setting q home 
    mkdir q
    copy %(conda info --base)%/q C:\q
    echo|set /P =%QLIC_KC% >q\kc.lic.enc
    certutil -decode q\kc.lic.enc q\kc.lic
    set QHOME=%cd%\q
    set PATH=%QHOME%\w64;%PATH%
    if not defined QLIC_KC (
      goto :nokdb
     )
deploy:

 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
